import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('src/components/modules/FinancialReportsView.tsx', 'utf8');
const root = source.match(/return \(\s*<div className="([^"]+)">\s*<PageHeader/);
assert.ok(root, 'financial reports root container was not found');
assert.equal(root[1], 'space-y-6 animate-fade-in');
assert.doesNotMatch(root[1], /bg-|background|min-h-screen/);
assert.match(source, /const specs = scopedEntities\.map\(entity =>/);
assert.match(source, /return scopedCC\.map\(cc =>/);
assert.match(source, /return scopedEntities\.flatMap\(en =>/);
assert.match(source, /key: `\$\{spec\.key\}-\$\{code\}`/);
assert.match(source, /printableStatementSpecs\.map\(spec =>/);
assert.match(source, /'EMPLOYEES_REPORT',[\s\S]*'CUSTOMERS_REPORT',[\s\S]*'VENDORS_REPORT',[\s\S]*'TRUSTS_REPORT',[\s\S]*'COST_CENTERS'/);
assert.match(source, /!usesDirectAnalyticalSelection && \(/);
assert.match(source, /الحساب التحليلي — سلف الموظفين الشهرية/);
assert.match(source, /الحساب التحليلي — عُهد الموظفين/);
assert.match(source, /normalizeVoucherSourceJournalCurrencies/);
assert.match(source, /const isMonthlyEmployeeAdvanceAccount/);
assert.match(source, /code\.startsWith\('110206'\)/);
assert.match(source, /const pendingVoucherJournals = useMemo<JournalEntry\[\]>/);
assert.match(source, /voucher\.status === 'VOIDED' \|\| knownJournalIds\.has\(voucher\.id\) \|\| knownDocumentNumbers\.has\(documentNumber\)/);
assert.match(source, /\[\.\.\.journals\.filter\(journal => journal\.status !== 'VOIDED'\), \...pendingVoucherJournals\]/);
assert.match(source, /v\.status !== 'VOIDED' && \(!isOriginalCurrencyReport/);
assert.match(source, /v\.status !== 'VOIDED'\) map\[`pending-voucher-\$\{v\.id\}`\] = 'سند صرف نقدي'/);
assert.match(source, /r\.status !== 'VOIDED'\) map\[`pending-voucher-\$\{r\.id\}`\] = 'سند قبض نقدي'/);
assert.doesNotMatch(source, /journal\.type === 'PV' && journal\.referenceCode === voucher\.voucherNumber/);
assert.match(source, /Custody amounts are persisted in their stated currency/);
assert.match(source, /PrintableCustodyStatement/);
assert.match(source, /titleAr: isSummary \? 'كشف مراكز التكلفة الإجمالي' : 'كشف مراكز التكلفة التحليلي'/);
assert.match(source, /const summaryTitleAr = statementSpecs\[0\]\?\.titleAr \|\| `كشف \$\{REPORT_META\[reportType\]\.ar\} الإجمالي`/);
assert.doesNotMatch(source, /titleAr: `\$\{REPORT_META\[reportType\]\.ar\} الإجمالي`/);
assert.match(source, /disbursementMethod: method/);
assert.match(source, /sourceName/);
assert.match(source, /costCenter:/);
assert.match(source, /debit: round2\(t\.amount \|\| 0\)/);
assert.match(source, /credit: round2\(\(t\.settledAmount \|\| 0\) \+ \(t\.returnedAmount \|\| 0\)\)/);
assert.doesNotMatch(source, /t\.amount \|\| 0\) \* \(isOriginalCurrencyReport/);
assert.match(source, /summarizeStatementsByCurrency\(statementSpecs, baseCode\)/);
assert.match(source, /Each entity \/ cost centre[\s\S]*original currency is represented by one summary row/);
assert.match(source, /!isSummary && groupedTB\.groups\.flatMap/);
assert.match(source, /إجمالي القيود اليومية/);
console.log('FINANCIAL_REPORTS_BACKGROUND_OK inheritedShell=true standaloneBackground=false matchesOtherModules=true entitySections=true currencySections=true combinedPrintJob=true summarySuppressesDetails=true pendingVouchersVisible=true analyticalProjection=true');
