import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync('src/components/modules/FinancialReportsView.tsx', 'utf8');
const root = source.match(/return \(\s*<div className="([^"]+)">\s*<PageHeader/);
assert.ok(root, 'financial reports root container was not found');
assert.equal(root[1], 'space-y-6 animate-fade-in');
assert.doesNotMatch(root[1], /bg-|background|min-h-screen/);
assert.match(source, /const specs = scopedEntities\.map\(entity =>/);
assert.match(source, /return scopedCC\.map\(cc =>/);
assert.match(source, /return scopedEntities\.flatMap\(en =>/);
assert.match(source, /key: `\$\{spec\.key\}-\$\{code\}`/);
assert.match(source, /printableStatementSpecs\.map\(spec =>/);
assert.match(source, /'EMPLOYEES_REPORT',[\s\S]*'CUSTOMERS_REPORT',[\s\S]*'VENDORS_REPORT',[\s\S]*'TRUSTS_REPORT',[\s\S]*'COST_CENTERS'/);
assert.match(source, /!usesDirectAnalyticalSelection && \(/);
assert.match(source, /الحساب التحليلي — سلف الموظفين الشهرية/);
assert.match(source, /الحساب التحليلي — عُهد الموظفين/);
assert.match(source, /normalizeVoucherSourceJournalCurrencies/);
assert.match(source, /Custody amounts are persisted in their stated currency/);
assert.match(source, /debit: round2\(t\.amount \|\| 0\)/);
assert.match(source, /credit: round2\(\(t\.settledAmount \|\| 0\) \+ \(t\.returnedAmount \|\| 0\)\)/);
assert.doesNotMatch(source, /t\.amount \|\| 0\) \* \(isOriginalCurrencyReport/);
assert.match(source, /if \(isSummary\) \{[\s\S]*summaryRows/);
assert.match(source, /كل كيان أو مركز تكلفة وعملة يظهر في سطر إجمالي واحد/);
assert.match(source, /!isSummary && groupedTB\.groups\.flatMap/);
assert.match(source, /إجمالي القيود اليومية/);
console.log('FINANCIAL_REPORTS_BACKGROUND_OK inheritedShell=true standaloneBackground=false matchesOtherModules=true entitySections=true currencySections=true combinedPrintJob=true summarySuppressesDetails=true');
