import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(file:string)=>fs.readFileSync(file,'utf8');
const layout=read('electron/report-layout.mjs'),pdf=read('electron/report-pdf.mjs');
assert.match(layout,/min-height:0!important/);
assert.match(pdf,/displayHeaderFooter: true/);
assert.match(pdf,/footerTemplate:/);
assert.match(pdf,/class="pageNumber"/);assert.match(pdf,/class="totalPages"/);
assert.match(pdf,/bottom: 18\/25.4/);
assert.match(pdf,/\.frp-page-foot,.report-footer,.statement-page-footer \{ display:none!important/);
assert.match(read('electron/main.mjs'),/await renderReportPdf\(printSource\)/);
for(const file of ['BaseReportTemplate','ReportPageTemplate']) assert.match(read(`src/components/ui/${file}.tsx`),/FinancialReportPrintLayout/);
assert.match(read('src/utils/voucherPdf.ts'),/desktopReportPdfBytes/);
console.log('REPORT_FOOTER_BOTTOM_OK sharedGeometry=true nativeEveryPageFooter=true reservedMargin=true realPageNumbers=true desktopExportUnified=true');
