import assert from 'node:assert/strict';
import {dateToIso,dateToDisplay,inDateRange} from '../src/utils/dateInput.ts';
import {reportDocuments,lineCostCenterId,entityOpening,lineBelongsToEntity,voucherReportAmount} from '../src/utils/reportData.ts';
import {projectJournalsToCurrency,projectPostedJournalsToCurrency} from '../src/utils/currencyReporting.ts';
import {requiredApprovalLevel,canApprove,approvalsComplete} from '../src/utils/custodyEngine.ts';
import {buildDisbursementJournal,buildSettlementJournal} from '../src/utils/custodyAccounting.ts';

assert.equal(dateToIso('٣٠/٠٨/٢٠٢٦'),'2026-08-30');
assert.equal(dateToIso('30082026'),'2026-08-30');
assert.equal(dateToDisplay('2026-08-30'),'30/08/2026');
assert.equal(dateToIso('31/02/2026'),'');assert.equal(dateToIso('29/02/2024'),'2024-02-29');
assert(inDateRange('30/08/2026','2026-08-01','2026-08-30'));
const j:any={id:'j1',entryNumber:'JV-1',date:'2026-08-30',currency:'YER',exchangeRate:1,status:'PENDING_POSTING',lines:[{accountId:'cash',debit:100,credit:0},{accountId:'income',debit:0,credit:100}],totalDebit:100,totalCredit:100};
const records=[j,{...j,id:'j2',status:'POSTED',date:'30/08/2026'},{...j,id:'void',status:'VOIDED'},{...j,id:'old',date:'2025-01-01'}];
assert.equal(reportDocuments(records,'2026-08-01','2026-08-30').length,2);
assert.equal(projectJournalsToCurrency([j], 'YER','YER',2,true)[0].status,'PENDING_POSTING');
assert.equal(projectPostedJournalsToCurrency([j],'YER','YER',2).length,0);
assert.equal(lineCostCenterId({costCenterId:'cc1'} as any),'cc1');
assert.equal(lineCostCenterId({subLedgerType:'COST_CENTER',subLedgerId:'cc2'} as any),'cc2');
const one={id:'box1',linkedAccountId:'cash',openingBalance:20},two={id:'box2',linkedAccountId:'cash',openingBalance:30};
assert.equal(entityOpening(one,'YER','YER'),20);
assert(!lineBelongsToEntity(j.lines[0],j,one,[one,two],['CASH_BOX']));
assert(lineBelongsToEntity({...j.lines[0],subLedgerType:'CASH_BOX',subLedgerId:'box1'},j,one,[one,two],['CASH_BOX']));
assert(!lineBelongsToEntity({...j.lines[0],subLedgerType:'CASH_BOX',subLedgerId:'box2'},j,one,[one,two],['CASH_BOX']));
assert(lineBelongsToEntity(j.lines[0],j,one,[one,two],['CASH_BOX'],[{journalEntryId:'j1',sourceAccountId:'cash',sourceEntityId:'box1'}]));
assert(lineBelongsToEntity(j.lines[0],j,one,[one],['CASH_BOX']));
assert.equal(entityOpening({...one,openingBalances:[{currency:'USD',debit:10,credit:0,debitLocal:2500,creditLocal:0} as any]},'USD','YER'),10);
assert.equal(entityOpening({...one,openingBalances:[{currency:'USD',debit:10,credit:0,debitLocal:2500,creditLocal:0} as any]},'YER','YER'),2500);
for(const amount of [1,10001,50001,100001,999999999])assert.equal(requiredApprovalLevel(amount),1);
const custody:any={id:'c',status:'PENDING_APPROVAL',approvals:[{level:1,action:'APPROVED'},{level:2,action:'PENDING'},{level:3,action:'PENDING'}],amount:100,custodyNumber:'CST-1',title:'Test',employeeId:'e',employeeName:'Test',disbursementSource:'box1',disbursementMethod:'CASH',costCenterId:'cc',disbursedAmount:100,settledAmount:0,refundedAmount:0,apTransferredAmount:0};
assert(canApprove(custody,1));assert(!canApprove(custody,2));assert(!canApprove({...custody,status:'DISBURSED'},1));
assert(approvalsComplete([{level:1,action:'APPROVED'}] as any,1));
const ctx:any={journalId:'j',entryNumber:'JV-1',currency:'YER',exchangeRate:1,createdBy:'test',reference:'CST-1'};
const disb=buildDisbursementJournal(ctx,custody,{id:'adv'} as any,{id:'cash'} as any);
assert.equal(disb.lines[0].costCenterId,'cc');assert.equal(disb.lines[1].subLedgerId,'box1');assert.equal(disb.totalDebit,disb.totalCredit);
const settle=buildSettlementJournal(ctx,custody,[{accountId:'expense',amount:100,total:100,taxAmount:0,costCenterId:'cc-special'}] as any,{id:'adv'} as any,null,null);
assert.equal(settle.lines[0].costCenterId,'cc-special');assert.equal(settle.totalDebit,settle.totalCredit);
assert.equal(voucherReportAmount({currency:'USD',exchangeRate:250,totalAmount:10},'YER','YER'),2500);
assert.equal(voucherReportAmount({currency:'USD',exchangeRate:250,totalAmount:10},'USD','YER'),10);
assert.equal(projectJournalsToCurrency([{...j,currency:'USD',exchangeRate:250,lines:[{accountId:'cash',debit:2500,credit:0}]}],'USD','YER',2,true)[0].lines[0].debit,10);
console.log('REPORT_SYSTEM_LOGIC_OK dates=valid/invalid/Arabic documents=pending+posted voidExcluded=true financialPendingExcluded=true costCenters=direct+helper entityIsolation=true entityOpenings=true approvals=oneStage+legacyPending custodyCostCenter=true');
