import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { initialCurrencies } from '../src/data/initialData';

const root = path.resolve(import.meta.dirname, '..');
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8');
assert.deepEqual(initialCurrencies.map(currency => currency.code), ['YER', 'SAR', 'USD']);
const app = read('src/App.tsx');
assert.match(app, /new Set\(\['AED', 'EUR', 'GBP'\]\)/);
assert.doesNotMatch(app, /DuplicateReviewView|case 'DATA_QUALITY'/);
assert.doesNotMatch(read('src/constants/permissions.ts'), /DATA_QUALITY/);
assert.doesNotMatch(read('src/components/modules/InputsView.tsx'), /جودة البيانات|DATA_QUALITY/);

const controller = read('src/components/ui/TableCollapseController.tsx');
const css = read('src/index.css');
assert.match(controller, /ltr \? row\.cells\[row\.cells\.length - 1\] : row\.cells\[0\]/);
assert.match(controller, /button\.onclick = event =>/);
assert.doesNotMatch(controller, /document\.addEventListener\('click', onClick, true\)/);
assert.match(controller, /button\.parentElement !== anchor/);
assert.match(css, /\.table-collapse-anchor\s*\{[^}]*height: 3\.5rem !important;/s);
assert.match(css, /\.table-collapse-anchor\s*\{[^}]*padding-top: 0\.5rem !important;[^}]*padding-right: 3\.5rem !important;[^}]*padding-bottom: 0\.5rem !important;[^}]*padding-left: 0\.5rem !important;/s);
assert.match(css, /\.table-collapse-toggle\s*\{[^}]*right: 0\.5rem;/s);
const chart = read('src/components/modules/ChartOfAccountsView.tsx');
assert.match(chart, /العملات \(تضمين \/ توقيف\)/);
assert.match(chart, /text-slate-700 dark:text-slate-300/);
assert.match(chart, /bg-sky-100 text-sky-700[^}]*dark:bg-sky-500\/15 dark:text-sky-200/);
assert.match(chart, /bg-slate-100 text-slate-600[^}]*dark:bg-slate-900 dark:text-slate-400/);

assert.doesNotMatch(chart, /إدارة عملات الحساب|نوع الحساب المساعد \(Sub-Ledger\)/);
const home = read('src/components/modules/HomePageView.tsx');
assert.match(home, /grid-cols-1 sm:grid-cols-2 lg:grid-cols-3/);
const sidebar = read('src/components/Sidebar.tsx');
assert.match(sidebar, /collapsed \? 'w-20' : 'w-64'/);
const f9 = read('src/components/ui/F9SearchInput.tsx');
assert.match(f9, /requestAnimationFrame\(\(\) => inputRef\.current\?\.focus/);
const f9Input = read('src/components/ui/F9SearchInput.tsx');
assert.match(f9Input, /e\.key === 'Enter' && onEnter/);
const journalAmounts = read('src/components/modules/JournalEntriesView.tsx');
assert.match(journalAmounts, /updated\[side\] = round2\(val\)/);
assert.match(journalAmounts, /label: 'رقم المرجع', value: selectedEntry\.reference \|\| '—'/);
assert.match(journalAmounts, /<th>رقم المرجع<\/th>/);
assert.match(journalAmounts, /\{line\.referenceNumber \|\| '—'\}/);
assert.match(journalAmounts, /\{line\.subLedgerName \|\| line\.accountNameAr\}/);
assert.match(journalAmounts, /<td colSpan=\{6\} className="text-left font-bold">الإجمالي:/);
assert.match(journalAmounts, /<col style=\{\{ width: '20%' \}\} \/>[\s\S]*<col style=\{\{ width: '23%' \}\} \/>/);
const currencyMath = read('src/utils/currencyMath.ts');
assert.match(currencyMath, /field === 'foreign'/);
const journalSearch = read('src/components/modules/JournalSearchBar.tsx');
assert.doesNotMatch(journalSearch, /base\.slice\(0, 50\)/);
assert.match(journalSearch, /onMouseDown=\{e => \{ e\.preventDefault\(\); selectItem\(entry\); \}\}/);
const reports = read('src/components/modules/FinancialReportsView.tsx');
const financialReportLayout = read('src/components/reports/FinancialReportPrintLayout.tsx');
const desktopPrintPreview = read('src/utils/desktopPrintPreview.ts');
const electronMain = read('electron/main.mjs');
const electronPreload = read('electron/preload.mjs');
const reportPage = read('src/components/ui/ReportPageTemplate.tsx');
assert.match(reports, /return \{ rangeLo: Math\.min\(lo, hi\), rangeHi: Math\.max\(lo, hi\) \};/);
assert.match(read('src/index.css'), /button\.light-primary-button[\s\S]*-webkit-text-fill-color: #ffffff !important/);
assert.match(read('src/index.css'), /sidebar-nav-label[\s\S]*color: #334155 !important/);
assert.ok(!read('electron/report-layout.mjs').includes('(?:رقم )?(?:المرجع'));
assert.doesNotMatch(read('electron/report-layout.mjs'), /th:first-child:not\(\[colspan\]\)/);
assert.match(read('electron/report-layout.mjs'), /hasNumberColumn/);
assert.match(read('electron/report-layout.mjs'), /numberHead\.textContent = '#'/);
assert.match(read('electron/report-layout.mjs'), /numberCell\.textContent = String\(\+\+rowNumber\)/);
assert.match(read('electron/report-layout.mjs'), /colgroup\.insertBefore\(numberCol, colgroup\.firstElementChild\)/);
assert.match(read('src/components/modules/FinancialReportsView.tsx'), /font-size: 7\.2px/);
assert.match(reports, /printableStatementSpecs/);
assert.match(reports, /full independent page per currency/);
assert.doesNotMatch(reportPage, /المرجع\|مستند المصدر/);
assert.match(reportPage, /reportSubtitle && entry\.label === 'رقم المستند'/);
const payment = read('src/components/modules/PaymentVouchersView.tsx');
const receipt = read('src/components/modules/ReceiptVouchersWindow.tsx');
assert.match(payment, /paymentMethod === 'CHEQUE' \? b\.entityType === 'BANK' : b\.entityType === 'EXCHANGE'/);
assert.match(receipt, /receiptMethod === 'CHEQUE' \? b\.entityType === 'BANK' : b\.entityType === 'EXCHANGE'/);
assert.match(receipt, />سعر الصرف<|>سعر الصرف<\/label>/);
assert.match(receipt, />المبلغ المحلي<|>المبلغ المحلي<\/label>/);
assert.match(payment, /value: selectedVoucher\.referenceNumber \|\| '—'/);
assert.match(receipt, /value: selectedReceipt\.referenceNumber \|\| '—'/);
assert.match(payment, /رقم المرجع للطرف/);
assert.match(receipt, /رقم المرجع للطرف/);
assert.match(payment, /data-enter-nav-field=\"account-name\"/);
assert.match(receipt, /data-enter-nav-field=\"account-name\"/);
assert.match(read('src/hooks/useEnterAsTab.ts'), /data-enter-nav-field/);
assert.match(payment, /f9SearchRef/);
assert.match(receipt, /f9SearchRef/);
assert.match(payment, /ArrowDown/);
assert.match(receipt, /ArrowDown/);
assert.match(payment, /const foreign = rate > 0 \? Math\.round\(\(val \/ rate\) \* 100\) \/ 100 : 0/);
assert.match(receipt, /const foreign = rate > 0 \? Math\.round\(\(val \/ rate\) \* 100\) \/ 100 : 0/);
assert.match(payment, /handleCurrencyFieldChange\('foreign'/);
assert.match(receipt, /handleCurrencyFieldChange\('foreign'/);
assert.doesNotMatch(payment, /المبلغ المحلي \(\$\{baseCode\}\\\)/);
assert.doesNotMatch(receipt, /المبلغ المحلي \(\$\{baseCode\}\\\)/);
assert.doesNotMatch(payment, /alert\(/);
assert.doesNotMatch(receipt, /alert\(/);
assert.match(payment, /toast\('error'/);
assert.match(receipt, /toast\('error'/);
assert.match(payment, /l\.referenceNumber \|\| '—'/);
assert.match(receipt, /l\.referenceNumber \|\| '—'/);
assert.match(payment, /onSelect=\{v => setSearchTerm\(v\.voucherNumber\)\}/);
assert.match(receipt, /onSelect=\{r => setSearchTerm\(r\.receiptNumber\)\}/);
assert.match(payment, /resolveSubLedgerName\(subLedgerDataset, type, subLedgerId\)/);
assert.match(payment, /\{reportAccountName\(l\)\}/);
assert.match(receipt, /resolveSubLedgerName\(subLedgerDataset, type, subLedgerId\)/);
assert.match(receipt, /\{reportAccountName\(l\)\}/);
assert.match(payment, /linkedLine\?\.subLedgerName/);
assert.match(receipt, /linkedLine\?\.subLedgerName/);
assert.match(payment, /entry\.type === 'PV' && entry\.referenceCode === selectedVoucher\?\.voucherNumber/);
assert.match(receipt, /entry\.type === 'RV' && entry\.referenceCode === selectedReceipt\?\.receiptNumber/);
for (const voucherReport of [payment, receipt]) {
  assert.match(voucherReport, /\? 'رقم الشيك'/);
  assert.match(voucherReport, /\? 'رقم الحوالة \/ الإشعار البنكي'/);
  assert.match(voucherReport, /: 'رقم الإيصال \/ المرجع'/);
  assert.match(voucherReport, /label: 'البيان العام', value: selected(?:Voucher|Receipt)\.narration \|\| '—'/);
}
assert.match(read('src/components/ui/SubLedgerF9Cell.tsx'), /registerScopedShortcut\(\{[\s\S]*key: 'F9'/);
const search = read('src/components/modules/opening/SavedBalancesSearch.tsx');
assert.doesNotMatch(search, /<Eye|فتح نافذة استعراض جميع الأرصدة المحفوظة/);
assert.match(read('src/components/reports/FinancialReportPrintLayout.tsx'), /\.frp-report-title[\s\S]*border: 0;/);
assert.match(css, /\.rpt-logo[\s\S]*width: 84px;[\s\S]*height: 84px;/);

const opening = read('src/components/modules/OpeningBalancesView.tsx');
assert.match(opening, /loadSavedIntoMainGrid/);
assert.doesNotMatch(opening, /<SavedBalancesModal|isBrowseOpen/);

const report = read('electron/report-layout.mjs');
assert.match(report, /font-size:7\.2px!important/);
assert.doesNotMatch(report, /data-report-fit/);
assert.match(report, /overflow:hidden!important/);
assert.match(report, /overflow-wrap:anywhere!important/);
assert.match(report, /word-break:break-word!important/);
assert.match(report, /white-space:normal!important/);
assert.doesNotMatch(report, /white-space:nowrap!important/);
assert.match(report, /thead th \{ text-align:center!important; \}/);
assert.match(css, /:where\(table\) thead th \{\s*text-align: center !important;/);
assert.match(css, /button\.financial-reports-show-button[\s\S]*color: #ffffff !important;/);
assert.match(reports, /className="financial-reports-show-button[^\"]*text-white/);
assert.doesNotMatch(financialReportLayout, /useLayoutEffect|normalizeReport\(root\)|ref=\{rootRef\}/);
assert.match(desktopPrintPreview, /const clone = element\.cloneNode\(true\)[\s\S]*normalizeReport\(clone\)/);
assert.match(electronMain, /zoomFactor: uiScaleToZoomFactor\(readUiScalePercent\(\)\)/);
assert.match(electronMain, /desktop-window:set-ui-scale[\s\S]*setZoomFactor\(zoomFactor\)/);
assert.match(electronMain, /bindConfiguredUiScale\(window, readUiScalePercent\)/);
const uiScaleRuntime = read('electron/ui-scale.mjs');
assert.match(uiScaleRuntime, /UI_ZOOM_BASE_FACTOR = 0\.7/);
assert.match(uiScaleRuntime, /zoom-changed[\s\S]*before-input-event[\s\S]*setInterval\(enforce, driftCheckMs\)/);
assert.match(electronPreload, /setUiScalePercent: percent => ipcRenderer\.sendSync\('desktop-window:set-ui-scale', percent\)/);
assert.match(read('src/components/modules/SettingsView.tsx'), /uiScalePercent: '100'[\s\S]*id="ui-scale-range"[\s\S]*min="50"[\s\S]*max="200"/);
assert.match(report, /table-layout:fixed/);
assert.match(report, /line-height:1.2!important/);
assert.match(report, /th \{ font-size:8px/);
assert.match(report, /width:96%/);
assert.match(report, /\[data-report-row-number\] \{ width:3%/);
assert.match(opening, /inline-flex w-full items-center justify-between/);
const auditView = read('src/components/modules/AuditAndSecurityView.tsx');
assert.doesNotMatch(auditView, /isTableExpanded|setIsTableExpanded/);
assert.doesNotMatch(auditView, /title=\{isTableExpanded \? 'طي الجدول' : 'توسيع الجدول'\}/);
assert.match(auditView, /<tbody className="divide-y divide-slate-800\/60">/);
assert.match(auditView, /<td colSpan=\{6\} className="p-14 text-center">/);

const aboutUs = read('src/components/modules/AboutUs.tsx');
assert.match(aboutUs, /github: 'alhomidyyasser-cmyk'/);
assert.match(aboutUs, /name: 'أحمد إسماعيل إبراهيم', role: 'مدير المنتج ومصمم تجربة وواجهات المستخدم ومهندس ضمان الجودة'[\s\S]*github: 'ia2d'/);
assert.match(aboutUs, /name: 'Ahmed Ismail Ibrahim', role: 'Product Manager, UI\/UX Designer & QA Engineer'/);
assert.match(aboutUs, /name: 'ياسر محمد الحميدي', role: 'المطور الرئيسي'/);
assert.match(aboutUs, /name: 'عبد الملك علي الريمي', role: 'المستشار المحاسبي'[\s\S]*linkedin: 'noon-erp'/);
assert.match(aboutUs, /src="\.\/brand\/fullerp-icon-128\.png" alt="NOON ERP"/);
assert.match(aboutUs, /src="\.\/brand\/fullerp-icon-dark-128\.png" alt="NOON ERP"/);
assert.doesNotMatch(aboutUs, /name: 'ياسر محمد ياسر'[^\n]*linkedin|name: 'أحمد إسماعيل إبراهيم'[^\n]*linkedin/);
assert.match(aboutUs, /https:\/\/www\.linkedin\.com\/in\/\$\{m\.linkedin\}/);

const enter = read('src/hooks/useEnterAsTab.ts');
const amount = read('src/components/AmountInput.tsx');
assert.match(enter, /not\(\[readonly\]\)/);
assert.match(amount, /if \(readOnly \|\| disabled\) return/);

const custody = read('src/components/modules/CustodyView.tsx');
assert.match(custody, /min-w-\[1540px\] table-fixed/);
assert.match(custody, /formatDate\(c\.expectedClearanceDate\)/);
assert.match(custody, /formatDate\(c\.requestedDate\)/);

console.log('SYSTEM_UI_FIXES_OK currencies=YER/SAR/USD collapse=direct-single-click+top-right chartCurrencies=restored opening=main-grid reportCells=static-font journalReadonlyNavigation=preserved dataQuality=removed custody=spaced-columns');
